### ISSUE TITLE
Value for CSP header

### ISSUE THREAD

**Issue by iresharma** [rudderlabs/rudder-sdk-js#1025]
Hey team,
I am trying to integrate rudderstack into our website, so I just wanted a list of domains I should add to CSP header whitelist .

**Comment by saikumarrs** [comment]
Hi @iresharma 
Source Configuration - `https://api.rudderlabs.com`
SDKs - `https://cdn.rudderlabs.com`

For each device mode destination, you can refer to the first note under the "Getting Started" section of the docs page for the URL we load their SDK from.

Example for VWO destination - https://www.rudderstack.com/docs/destinations/streaming-destinations/vwo/#getting-started
