### ISSUE TITLE
Properties in page call are broken

### ISSUE THREAD

**Issue by jb33k** [rudderlabs/rudder-sdk-js#103]
I'm trying to get `rudderstack.page()` call to work but it doesn't want to accept custom properties for some reason.

This doesn't work:
```
const path = '/foobar/'
rudderanalytics.page({ path })
```
When I look at the request browser sends, I see ` { ... properties: { path: '/' ... }}`, so for some reason `path` is not picked up, as well as all other custom properties.

I'm following this documentation: https://docs.rudderstack.com/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk#3-3-page

However, it does work if I add category and name, which are suppose to be optional, i.e.:
```
const path = '/foobar/'
rudderanalytics.page('foo', 'bar', { path })
```

**Comment by sayan-mitra** [comment]
Thanks for reaching out.
we will take a look and get back

**Comment by sayan-mitra** [comment]
we have updated our sdk.
please let us know if it solved the above.
