### ISSUE TITLE
BUG : Rudderstack does not respect `integrations` field in the `load()` function

### ISSUE THREAD

**Issue by usovigorok** [rudderlabs/rudder-sdk-js#1041]
**Describe the bug**
Rudderstack does not respect the `integrations` field in the `load()` function, though e.g. another field `uaChTrackLevel` is respected.

**To Reproduce**

Call `window.rudderanalytics.load(KEY, URL, {integrations: {All: false}})`

**Expected behavior**

after the `load` function call in the following events, I would expect to see `{integrations: {All: false}}`, but I see always `{integrations: {All: true}}`.

This issue happens only for the `integrations` field in the `load()` function, other fields are respected.

**Additional Information:**

- SDK installation: CDN
- CDN URL: https://cdn.rudderlabs.com/v1.1/rudder-analytics.min.js
- Used JS Framework: NextJS

**Desktop:**

- OS: Mac OS
- Browser: Chrome
- Version: 112

**Comment by MoumitaM** [comment]
@usovigorok, Thank you for flagging this. We will look into it soon.

**Comment by MoumitaM** [comment]
Hello @usovigorok, We released a new version of the SDK yesterday and resolved this with a flag. For more info: [reference](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk/#useglobalintegrationsconfiginevents)
Do try it out.

**Comment by usovigorok** [comment]
Hello @MoumitaM,

Great, thank you, we will try it out.
