### ISSUE TITLE
FB pixel integration not working with Cordova

### ISSUE THREAD

**Issue by jb33k** [rudderlabs/rudder-sdk-js#106]
`[Util] handleError::  error in script loading:: src::  file://connect.facebook.net/en_US/fbevents.js id:: fbpixel-integration`

I'm guessing you are using `window.location.protocol` to load the script. This won't work with Cordova because everything is loading from `file://`.

Is there anyway to force `https://` protocol for scripts?

**Comment by sayan-mitra** [comment]
thanks for pointing out.
we started looking into this.

**Comment by sayan-mitra** [comment]
we have updated our sdk.
please let us know if it solved your usecase.
