### ISSUE TITLE
Feature Request: Types of function arguments to be exported

### ISSUE THREAD

**Issue by ymmooot** [rudderlabs/rudder-sdk-js#1130]
Hi ruuderlabs, thank you for the nice SDK.

**Is your feature request related to a problem? Please describe.**

When I tryied to create some wrapper program of the SDK, I could not get the type of `properties` which is an argument of `track` function.
`properties` is actually `apiObject` but I can not import from the SDK.
That's why I did this:

```ts
type APIObject = (typeof rudder.track) extends {
  (event: string, properties?: infer A, options?: infer B, callback?: infer C): void;
  (event: string, properties: infer A, callback: infer C): void;
  (event: string, callback: infer C): void;
} ? A : never;
```

This hack will stop working if there is a change in the SDK's function overload.

**Describe the solution you'd like**

I want to import it like: 

```ts
import { APIObject } from 'rudder-sdk-js';
```

**Describe alternatives you've considered**

Nothing.

**Additional context**

Nothing.

**Comment by saikumarrs** [comment]
Hi @ymmooot 
Since the SDK is not a TypeScript project, the [types declaration file](https://github.com/rudderlabs/rudder-sdk-js/blob/production-staging/packages/npm/index.d.ts) is manually created and added to the NPM package.

The types of all the API arguments are already exported.

Based on your use case, do you think this would work?

```
import * as rudderanalytics from "rudder-sdk-js";
import { apiObject } from "rudder-sdk-js";

...
// or const trackProperites: rudderanalytics.apiObject 
const trackProperites: apiObject = {
  prop1: "val1",
  prop2: "val2",
  prop3: false
};

rudderanaltyics.track("Sample track", trackProperites);
```

**Comment by ymmooot** [comment]
Hi @saikumarrs, thank you for your quick reply.
I did not realize that the type is exported 🙏 
Sorry about it.
Thank you!
