### ISSUE TITLE
A way to add a limit to the retries by rudder-js-sdk in case the request fails

### ISSUE THREAD

**Issue by so-sdhawan** [rudderlabs/rudder-sdk-js#130]
Rudder server was down for a few hours on environment, and server the got overloaded by the retry api request from rudder-sdk-js. Need a way to mitigate this.

**Comment by sayan-mitra** [comment]
Had a query:
Is the concern around the time when the server was down, the requests were high or once the server came back up and then it was flooded?
(Presently each failed request is tried at max 10 times with exponential backoff)

**Comment by so-sdhawan** [comment]
First one, the time when the server was down, the requests were high.

**Comment by sayan-mitra** [comment]
This change is in place for sometime. We missed to update here. Sorry for the same.
You can pass a key named **queueOptions** in the options param of load call as below:
 ```
rudderanalytics.load(YOUR_WRITE_KEY, DATA_PLANE_URL, {queueOptions: {
  maxRetryDelay: 360000,
  minRetryDelay: 1000,
  backoffFactor: 2,
  maxAttempts: 10,
  maxItems: 100,
}});
```

**Comment by sayan-mitra** [comment]
[Doc reference]( https://docs.rudderstack.com/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk#3-1-1-load-options)
