### ISSUE TITLE
Feature Request: Include `timezone` attribute in messages by default

### ISSUE THREAD

**Issue by orrc** [rudderlabs/rudder-sdk-js#1345]
**Is your feature request related to a problem? Please describe.**
We don't receive information on user device time zone in our RudderStack destinations when using this JS SDK.

**Describe the solution you'd like**
The RudderStack mobile SDKs automatically include the `timezone` [contextual attribute](https://www.rudderstack.com/docs/event-spec/standard-events/common-fields/#contextual-fields) in `identify`/`track` messages. It would be useful to have the same behaviour for the JS SDK.

The [`Intl DateTimeFormat API`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/resolvedOptions) was first introduced in 2012, and is [supported by](https://caniuse.com/mdn-javascript_builtins_intl_datetimeformat_resolvedoptions) virtually all browsers.

It returns a value in the IANA Time Zone Database format that RudderStack uses anyway.  
For example, in the Chrome console:
```
$ Intl.DateTimeFormat().resolvedOptions().timeZone
  'Europe/Berlin'
```

**Describe alternatives you've considered**
A workaround is to call the time zone API ourselves and add `timezone` as to `apiOptions` when calling `identify` etc., since arbitrary keys in `apiOptions` get merged into the `context` object.

**Additional context**
N/A

**Comment by bardisg** [comment]
Hello @orrc ,

Thank you for providing such detailed feature request. We evaluate this one with the product team and we will update you in the following days

**Comment by bardisg** [comment]
Hello @orrc,

Upcoming release will contain this feature.

**Comment by MoumitaM** [comment]
Hello @orrc, We have released the SDK which has timezone auto-captured by the SDK in this format: 
`timezone: "GMT+0530"`

**Comment by orrc** [comment]
Thanks! But I think the implementation is unhelpful, and potentially harmful.

My request was to return a value in the [IANA Time Zone Database format](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).
Some examples of these tzdb IDs:
- `Europe/Berlin`
- `America/Los_Angeles`
- `Etc/UTC`

---
The [Pull Request](https://github.com/rudderlabs/rudder-sdk-js/pull/1464) says:
> Following the same format as mobile. Example: "GMT+0530"

..but that doesn't seem to reflect reality:
- The RudderStack [Android SDK](https://github.com/rudderlabs/rudder-sdk-android/blob/v1.20.2/core/src/main/java/com/rudderstack/android/sdk/core/util/Utils.java#L56-L59) returns [`TimeZone#id`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/TimeZone.html#getID()) for the default time zone, which will be a tzdb ID
- The RudderStack [iOS SDK](https://github.com/rudderlabs/rudder-sdk-ios/blob/v1.23.0/Sources/Classes/RSContext.m#L43) uses the local `NSTimeZone` and returns a [tzdb ID](https://developer.apple.com/documentation/foundation/nstimezone?language=objc)

If I look at live RudderStack events coming from Android or iOS, I see only tzdb IDs in the `timezone` attribute.
If I query our data warehouse for `identify` events, I see 234 distinct values, all of which are tzdb IDs that came from:
- The RudderStack Android SDK,
- The RudderStack iOS SDK,
- our browser JS which adds `timezone: Intl.DateTimeFormat().resolvedOptions().timeZone | undefined` to our traits for RudderStack events

---
Furthermore, the current implementation (`"GMT+0530"`) is a bad idea because:
- It represents a time _offset_, and not a time _zone_:
  - Today `Europe/Berlin` is `GMT+0100` — but one week ago it was `GMT+0200` due to being in European summer time
  - Storing `GMT+0100` for my users doesn't allow me to calculate their _current_ time
- It's not recognised by software like a tzdb ID would be, even when reformatted as `GMT+05:30`
- It returns a totally weird value ([`"NA"`](https://github.com/rudderlabs/rudder-sdk-js/pull/1464/files#diff-89773e69beb086f5214e94cdb398c65f7b9b634822af36b7178e924546f39bb1R7)) if the time zone can't be parsed, instead of `undefined`

For example, right now I can run this query on our data warehouse (Postgres):
```sql
select distinct timezone, now() at time zone timezone
from rudderstack.identifies
where timezone is not null
order by 2
```

..and I get the expected answers:
```
Pacific/Honolulu   Nov 2, 2023, 01:23
Pacific/Tahiti     Nov 2, 2023, 01:23
America/Nome       Nov 2, 2023, 03:23
America/Anchorage  Nov 2, 2023, 03:23
US/Pacific         Nov 2, 2023, 04:23
…
```

However, if we start polluting it with non-standard values like `GMT+0530` (or `NA`) people's existing queries will fail:
```
select now() at time zone 'GMT+0530'
→ ERROR: time zone "GMT+0530" not recognized
```

This is perhaps Postgres-specific, but even changing `GMT+0530` to `GMT+05:30` won't work as expected:
```sql
-- Current time in UTC
select now() at time zone 'UTC'
→ Nov 2, 2023, 11:23

-- Inserted `:` into the time offset from the JS SDK,
-- will return value 5.5 hours *BEHIND* UTC, instead of ahead
select now() at time zone 'GMT+05:30'
→ Nov 2, 2023, 05:53

-- Switched `+` to `-` to match tzdb format (e.g. `Etc/GMT-5`)
select now() at time zone 'GMT-05:30'
→ Nov 2, 2023, 16:53

-- Used the expected tzdb format
select now() at time zone 'Asia/Kolkata'
→ Nov 2, 2023, 16:53
```

---
So I'm grateful for you checking out my feature request, but we 100% will not be able to use this implementation, and I hope that you might consider changing it.
