### ISSUE TITLE
BUG : @rudderstack/analytics-js/bundled isn't found when importing

### ISSUE THREAD

**Issue by riceboyler** [rudderlabs/rudder-sdk-js#1436]
**Describe the bug**
In the documentation for SDK v3, there is a section that says:
<img width="844" alt="image" src="https://github.com/rudderlabs/rudder-sdk-js/assets/2243596/7df8f638-205d-4d3f-9293-16ff9a67a5ef">

When changing the initialization code in my codebase to match this, the module is not found. (screenshot from build logs on Vercel):
<img width="1061" alt="image" src="https://github.com/rudderlabs/rudder-sdk-js/assets/2243596/49a16242-ec38-4380-8473-c9f2cf927635">

I find that if I don't point to the `/bundled` version, events don't get logged from my Next.js powered site.

**To Reproduce**
1. Install the SDK v3 package via npm/yarn/pnpm `pnpm add @rudderstack/analytics-js`
2. When importing from that package in a Next.js codebase, change to `import { RudderAnalytics } from '@ruddderstack/analytics-js` 

**Expected behavior**
Module should be found and not throw an error in either the IDE or in the build process.

**Screenshots**

**Additional Information (please complete the following information):**

- SDK installation: NPM
- NPM Version: 3.0.0-beta.12
- Webpage URL: Unfortunately, because it won't build, I can't get a public URL
- Share the event payload
- Next.js

**Desktop (please complete the following information):**

- OS: macOS 13.6
- Browser: Arc Browser (Chromium)
- Version: 1.11.0

**Additional context**
I tried removing the `bundled` extension for the module import and I get different errors at run-time and no events get logged. Interestingly, I can actually run the site fine on my localhost, but the build process breaks because it can't resolve the `bundled` module properly.

**Comment by bardisg** [comment]
Hello @riceboyler,

Thank you for raising this issue with us. 

I just created two new NextJs apps with Typescript and Javascript and both imported without any issues.

Would it be possible to provide more information please in order to replicate?

- What version of typescript and node are you on?
- Please provide the orchestration part of your code in order to replicate your exact scenario
- If possible, your typeScript config compiler options

**Comment by riceboyler** [comment]
@bardisg Thanks for the reply! Here's some more pertinent information:
- We're using Next.js v13.4 but we're still using the Page Router
- This all exists in an NX monorepo, and I believe they've recently switched from Babel to SWC for compiling (if that matters)
- I've cleared both the Next.js cache AND the pnpm cache (in case it was holding on to an old version for some reason)

Here's a screenshot from our package.json (using a VS Code extension that evaluates what's actually installed).
<img width="720" alt="image" src="https://github.com/rudderlabs/rudder-sdk-js/assets/2243596/9a9756c2-59e8-43df-94ab-af6c426b3753">

We're on Node v18.17.0 and TypeScript v5.2.2. As we're in a monorepo, we have the tsconfig files split, so here is the one in the tracking library (which is where we're doing everything related to Rudderstack):

```
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "jsx": "react-jsx",
    "strict": false,
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true
  },
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.lib.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
}
```

And this is the base tsconfig.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": [
      "es2017",
      "dom"
    ],
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {redacted, shouldn't be important}
  "exclude": [
    "node_modules",
    "tmp"
  ],
  "files": []
}

I've verified the version of @rudderstack/analytics-js in the node_modules folder to indeed be 3.0.0-beta.12. I see all of the files that should be there for the `/bundled` version to work.

Here's where we're attempting to load the library and getting the VSCode red squiggle (and where the Build process fails as well):

```typescript
import { RudderAnalytics, type ApiObject, type ApiCallback } from '@rudderstack/analytics-js/bundled';

import { ChapiModel } from '@chtbks/api';
import { config } from '@chtbks/config';
import { isServer } from '@chtbks/helpers';

declare global {
  interface Window {
    rudderanalytics: RudderAnalytics;
  }
}

let rudderAnalytics: RudderAnalytics;

export const isEnabled = () => {
  const envConfig = config();
  return envConfig.analytics.rudderstack.enabled;
};

export const isLoaded = () => {
  return Boolean(rudderAnalytics) && isEnabled() && !isServer() && window?.rudderanalytics;
};

export function load() {
  if (!isEnabled()) {
    return;
  }
  rudderAnalytics = new RudderAnalytics();
  const envConfig = config();

  rudderAnalytics.load(envConfig.analytics.rudderstack.writeKey, envConfig.analytics.rudderstack.dataPlaneUrl);

  if (!isLoaded() && !isServer()) {
    window.rudderanalytics = rudderAnalytics;
  }
}
```

I think that covers everything you asked for. I'm going to try creating a new NX monorepo and see if it works in there, as I have this sneaky suspicion the problem could be related to some conflict between NX and the bundling method.

**Comment by riceboyler** [comment]
Just created a new NX monorepo, added @rudderstack/analytics-js via pnpm and attempted to reference the `/bundled` module and I'm getting the exact same error, so that makes me think maybe there's something with how NX references packages internally that's making it not respect the `/bundled`.

**Comment by riceboyler** [comment]
One more note, I tried a workaround of pointing directly to `@rudderstack/analytics-js/dist/npm/modern/bundled/esm` and it got rid of the VS Code error, but on build I get: 
```
Module not found: Package path ./dist/npm/modern/bundled/esm/index is not exported from package /Users/riceboyler/source/@chtbks/nx-web/node_modules/@rudderstack/analytics-js (see exports field in /Users/riceboyler/source/@chtbks/nx-web/node_modules/@rudderstack/analytics-js/package.json)
```

I added an export in the node_modules/package.json pointing to the path I tried to use and it now builds properly, so it must be something related to how the exports are handled by NX.

**Comment by riceboyler** [comment]
FWIW, I created a bug in the NX repo for this as well, since I think it's more of an NX problem: https://github.com/nrwl/nx/issues/19563

**Comment by riceboyler** [comment]
Create a PR (#1442 ) as a workaround solution for this issue until a permanent solution can be provided by either Rudderstack or NX.

**Comment by riceboyler** [comment]
Thanks @bardisg . Thanks to your suggested, TIL about `pnpm patch` and pnpm patch-commit`!

**Comment by riceboyler** [comment]
And of course, NX doesn't properly work with `pnpm patch` because it doesn't copy the patchedDependencies section over. I'm going to try with patch-package and see if it's better supported.

**Comment by bardisg** [comment]
Hello @riceboyler,

I have been using patch-package with nx for a while with no issues. I have my patches dependencies as part of the root level package.json. Usind also in this repo if you like to see an example.

I have tested other packages with consitional package exports and they have the same issue with nx. Will try to find some time to see if I can fix it for NX.

Will follow up on your opened issue there if I have any more findings

**Comment by bardisg** [comment]
Hello @riceboyler ,

From next release you will not need to use the "/bundled" as the issue with webpack has been resolved.

**Comment by MoumitaM** [comment]
Hello @riceboyler, SDK has been released. No need to use "/bundled" in the import anymore.

**Comment by jcurtis** [comment]
This should be removed from the documentation site since it's misleading now https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-javascript-sdk/v3/#sdk-imports-for-bundling-tools-that-process-dynamic-imports
