### ISSUE TITLE
BUG : Common types not accepted for TypeScript files

### ISSUE THREAD

**Issue by Kwilliams-dev303** [rudderlabs/rudder-sdk-js#1524]
**Describe the bug**
There are some common types that are not accepted by the SDK.

**To Reproduce**

1. In an example that uses rudder-sdk-js 2.40, pass in a value with type Date, or null into the second param of a track call. In a .ts, .tsx file, this should cause a type error. As it does not match the apiObject type. 

**Expected behavior**
Common types like null or Date to be accepted.

**Screenshots**
![image](https://github.com/rudderlabs/rudder-sdk-js/assets/105746701/7206c4bf-6741-4342-ba6b-bede1cc4b3b8)

If I add this to your index.d.ts file, several different type errors are resolved in my code.

`/**
   * Represents a generic object in the APIs
   * Use for parameters like properties, traits etc.
   */
  interface apiObject {
    [index: string]:
      | string
      | number
      | boolean
      | apiObject
      | (string | number | boolean | apiObject | undefined | null | Date)[]
      | undefined
      | null
      | Date;
  }`

**Additional Information (please complete the following information):**

- SDK installation: npm
- NPM Version: 2.40.0
- Used JS Framework: React

**Comment by bardisg** [comment]
Hello @Kwilliams-dev303 ,

Thank you for bringing this issue in our attention. 

We will evaluate if the values of the desired types work as expected end to end in our pipeline and will inform you for the next steps.

**Comment by MoumitaM** [comment]
Hello, we are adding these new types in our latest SDK(v3).

**Comment by saikumarrs** [comment]
Hello @Kwilliams-dev303, 
We've updated the SDK to add the support for the types you've requested.
