### ISSUE TITLE
Unnecessary error log for Google Ads

### ISSUE THREAD

**Issue by nfiacco** [rudderlabs/rudder-sdk-js#1546]
Won't `name` sometimes be empty for page events?

https://github.com/rudderlabs/rudder-sdk-js/blob/98bcdf7aaaec1ed4512352d8fb8982312c1fcef3/packages/analytics-js-integrations/src/integrations/GoogleAds/browser.js#L195-L198

**Comment by MoumitaM** [comment]
Hi @nfiacco, `name` might be empty for some page events but for Google Ads it is mandatory. We can not proceed without that.
CC @ItsSudip

**Comment by nfiacco** [comment]
I've filtered out the page events though. It's strange that it does the check without even checking if the event should be sent in the first place

**Comment by MoumitaM** [comment]
> I've filtered out the page events though. It's strange that it does the check without even checking if the event should be sent in the first 

I didn't get that.
Can you be a little more descriptive?

**Comment by nfiacco** [comment]
I don't want to send page events to Google Ads at all. So there shouldn't be an error right?

I've set up a filter so that only specific events should be sent, see the documentation for Conversion Event Filtering https://www.rudderstack.com/docs/destinations/streaming-destinations/g-ads-gtag/

**Comment by MoumitaM** [comment]
You can instrument your page call like below to skip google ads.

```
rudderanalytics.page(
  "page name/category", {
   properties
    },
    {
       integrations: {
          All: true,
          "Google Ads": false
       }
    });
```
 This is one way.
 @ItsSudip Can you look at the query and suggest the best possible way to achieve that?

**Comment by nfiacco** [comment]
That's helpful, but it still seems strange to me that an error would be logged when the event doesn't match the filters in `Conversion Event Filtering`. Or am I misunderstanding what that filter is for

**Comment by nfiacco** [comment]
Any update here?

**Comment by ItsSudip** [comment]
Hey @nfiacco,
I believe you are misunderstanding `Conversion Event Filtering`. That filter is for event names provided through track calls, which you can send in [this](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-javascript-sdk/quick-start-guide/#step-4-track-user-actions) (here `Order Completed` is the event name) way. 
Let me know if it resolves the misunderstanding.
Thanks.

**Comment by nfiacco** [comment]
Are you saying that `Conversion Event Filtering` only filters the track events? How can I filter out the page events then?

**Comment by nfiacco** [comment]
Also this doesn't answer my original question: how can I prevent the Google Ads integration from showing an error for every page event? I don't even want page events to be sent, so it should not matter that the event is missing the name field

**Comment by ItsSudip** [comment]
Hey @nfiacco you can use `Conversion Event Filtering` for page events as well. But for that, you need to provide the page event name. We are using the name parameter to filter in [page events](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-javascript-sdk/supported-api/#page). And [this](https://github.com/rudderlabs/rudder-sdk-js/blob/98bcdf7aaaec1ed4512352d8fb8982312c1fcef3/packages/analytics-js-integrations/src/integrations/GoogleAds/browser.js#L195-L198) error will occur if you are not providing the name, which is again required for event filtering.

**Comment by nfiacco** [comment]
Ok so how can I continue to use page events without a name, and not have this error show up? In my opinion this is a bug with the SDK

**Comment by ItsSudip** [comment]
You can't actually if you have enabled `Track Dynamic Remarketing` as we are using the name to filter and sending the name to Google through [gtag](https://github.com/rudderlabs/rudder-sdk-js/blob/dd086640a05da480d579b1580aad110b14c6165d/packages/analytics-js-integrations/src/integrations/GoogleAds/browser.js#L209). 
Anyway, the check seems like a bug, we will remove that check from there.

**Comment by nfiacco** [comment]
Any update on this?

**Comment by ItsSudip** [comment]
This is released. We have removed the unnecessary checks.
