### ISSUE TITLE
BUG: if SDK is blocked by ad blocker, SDK v3 usage results in error while legacy SDK usage results in undefined

### ISSUE THREAD

**Issue by Amaimersion** [rudderlabs/rudder-sdk-js#1563]
**Describe the bug**

I have this line in my code `window.rudderanalytics?.getAnonymousId()`. On page where RudderStack SDK is being loaded it gets blocked by Ad Blocker. In case of using legacy SDK I'm getting `undefined` as a result, which is wanted behavior. In case of using v3 SDK I'm getting error `Uncaught TypeError: window.rudderanalytics?.getAnonymousId is not a function`, which is not wanted behavior. 

**To Reproduce**

1. Open any page whose CSP allows loading of RudderStack SDK
2. Make sure Ad Blocker is enabled on this page. This Ad Blocker should support blocking of RudderStack SDK. I'm using [uBlock Origin](https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm)
3. Open developer console
4. Paste this code to load legacy SDK:
```js
!function(){var e=window.rudderanalytics=window.rudderanalytics||[];e.methods=["load","page","track","identify","alias","group","ready","reset","getAnonymousId","setAnonymousId","getUserId","getUserTraits","getGroupId","getGroupTraits","startSession","endSession"],e.factory=function(t){return function(){e.push([t].concat(Array.prototype.slice.call(arguments)))}};for(var t=0;t<e.methods.length;t++){var r=e.methods[t];e[r]=e.factory(r)}e.loadJS=function(e,t){var r=document.createElement("script");r.type="text/javascript",r.async=!0,r.src="https://cdn.rudderlabs.com/v1.1/rudder-analytics.min.js";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(r,a)},e.loadJS(),
e.load("abc","DATA_PLANE_URL"),
e.page()}();
```
5. In the console you should see this error: `GET https://cdn.rudderlabs.com/v1.1/rudder-analytics.min.js net::ERR_BLOCKED_BY_CLIENT`
6. Type `window.rudderanalytics?.getAnonymousId()`. You should get `undefined` as a result
7. Paste this code to load v3 SDK:
```js
!function(){"use strict";var sdkBaseUrl="https://cdn.rudderlabs.com/v3";var sdkName="rsa.min.js";var asyncScript=true
        ;window.rudderAnalyticsBuildType="legacy",window.rudderanalytics=[]
        ;var e=["setDefaultInstanceKey","load","ready","page","track","identify","alias","group","reset","setAnonymousId","startSession","endSession"]
        ;for(var t=0;t<e.length;t++){var n=e[t];window.rudderanalytics[n]=function(e){return function(){
        window.rudderanalytics.push([e].concat(Array.prototype.slice.call(arguments)))}}(n)}try{
        new Function('return import("")'),window.rudderAnalyticsBuildType="modern"}catch(a){}
        if(window.rudderAnalyticsMount=function(){
        "undefined"==typeof globalThis&&(Object.defineProperty(Object.prototype,"__globalThis_magic__",{get:function get(){
        return this},configurable:true}),__globalThis_magic__.globalThis=__globalThis_magic__,
        delete Object.prototype.__globalThis_magic__);var e=document.createElement("script")
        ;e.src="".concat(sdkBaseUrl,"/").concat(window.rudderAnalyticsBuildType,"/").concat(sdkName),e.async=asyncScript,
        document.head?document.head.appendChild(e):document.body.appendChild(e)
        },"undefined"==typeof Promise||"undefined"==typeof globalThis){var d=document.createElement("script")
        ;d.src="https://polyfill.io/v3/polyfill.min.js?features=Symbol%2CPromise&callback=rudderAnalyticsMount",
        d.async=asyncScript,document.head?document.head.appendChild(d):document.body.appendChild(d)}else{
        window.rudderAnalyticsMount()}window.rudderanalytics.load("abc","DATA_PLANE_URL",{})}(); 
```
8. In the console you should see this error: `GET https://cdn.rudderlabs.com/v3/modern/rsa.min.js net::ERR_BLOCKED_BY_CLIENT`
9. Type `window.rudderanalytics?.getAnonymousId()`. You should get `Uncaught TypeError: window.rudderanalytics?.getAnonymousId is not a function` as a result

**Expected behavior**

I'm expecting to get either anonymous ID or `undefined` in case if SDK is not loaded or blocked by ad blocker. Because ad blockers are using often nowadays, it is preferable that any interaction with `rudderanalytics` will not result in unexpected error, rather all methods should do nothing and all returns should be `undefined`. 

Otherwise I will have to add `if (window.rudderanalytics?.getAnonymousId)` in every place of my code where I'm using RudderStack v3 SDK, which obviously increases complexity of the code. More over, such moments makes it harder to migrate from the legacy SDK to the v3 SDK.

**Comment by MoumitaM** [comment]
Hi @Amaimersion  Thank you for raising this. `getAnonymousId` is supposed to be called after the SDK is loaded. But in your case, you can modify the loading script slightly to get the desired behavior.
Add `getAnonymousId` in the array mentioned below.

`var e=["setDefaultInstanceKey","load","ready","page","track","identify","alias","group","reset","setAnonymousId","startSession","endSession"]`

This is part of the loading script.

```
!function(){"use strict";var sdkBaseUrl="https://cdn.rudderlabs.com/v3";var sdkName="rsa.min.js";var asyncScript=true
        ;window.rudderAnalyticsBuildType="legacy",window.rudderanalytics=[]
        ;var e=["setDefaultInstanceKey","load","ready","page","track","identify","alias","group","reset","setAnonymousId","startSession","endSession", "getAnonymousId"]
        ;for(var t=0;t<e.length;t++){var n=e[t];window.rudderanalytics[n]=function(e){return function(){
        window.rudderanalytics.push([e].concat(Array.prototype.slice.call(arguments)))}}(n)}try{
        new Function('return import("")'),window.rudderAnalyticsBuildType="modern"}catch(a){}
        if(window.rudderAnalyticsMount=function(){
        "undefined"==typeof globalThis&&(Object.defineProperty(Object.prototype,"__globalThis_magic__",{get:function get(){
        return this},configurable:true}),__globalThis_magic__.globalThis=__globalThis_magic__,
        delete Object.prototype.__globalThis_magic__);var e=document.createElement("script")
        ;e.src="".concat(sdkBaseUrl,"/").concat(window.rudderAnalyticsBuildType,"/").concat(sdkName),e.async=asyncScript,
        document.head?document.head.appendChild(e):document.body.appendChild(e)
        },"undefined"==typeof Promise||"undefined"==typeof globalThis){var d=document.createElement("script")
        ;d.src="https://polyfill.io/v3/polyfill.min.js?features=Symbol%2CPromise&callback=rudderAnalyticsMount",
        d.async=asyncScript,document.head?document.head.appendChild(d):document.body.appendChild(d)}else{
        window.rudderAnalyticsMount()}window.rudderanalytics.load("abc","DATA_PLANE_URL",{})}(); 
```

**Comment by Amaimersion** [comment]
Thanks! That works. 

I wonder why not add this in default code  on destination setup page? I took both codes from setup page. Legacy setup code contain all methods in the array, why not do same for v3 code?

**Comment by MoumitaM** [comment]
@Amaimersion, Till the SDK is loaded properly these getter methods will not return the correct value. So it is meant to be called after SDK is loaded and it doesn't make sense to buffer the API. That is why we removed it in v3 script.

You should only call these methods when SDK is loaded. You can use the `onLoaded` load option or `ready` API to fetch these values.

**Comment by Amaimersion** [comment]
Got it. Thanks!
