### ISSUE TITLE
BUG : Category is used incorrectly as ContentType for FB Pixel

### ISSUE THREAD

**Issue by nfiacco** [rudderlabs/rudder-sdk-js#1597]
**Reviewers**: @shrouti @sudip @utsab 

**<Bug Summary>**

Identified by Customer or Developer: Customer

[https://github.com/rudderlabs/rudder-sdk-js/issues/1597](https://github.com/rudderlabs/rudder-sdk-js/issues/1597)

To review & fix `category` mapping for facebook pixel in device mode

* But the same mapping should be followed again in cloud mode too
* Consider backward compatibility of mapping fields

**References of the bug (Slack/CFD card)**

[https://www.notion.so/rudderstacks/Category-to-content_type-mapping-issue-a9ce8d8fb78041afa4b04b9bf54ca4c4](https://www.notion.so/rudderstacks/Category-to-content_type-mapping-issue-a9ce8d8fb78041afa4b04b9bf54ca4c4)

**Effected customers** 

| **Effected customers** | **Workspace ID** |
| -- | -- |
|  |  |
|  |  |

**Action items**

\[Mention action items - like events replay in case of data loss here\]

**<Checklist before moving to Development>**

---

* If there are any design-related discussions or changes that require a design review, please link the <design review card> here.
* Design/Research doc: <Link> 

* Test cases doc: <Link> (Refer template [here](https://www.notion.so/rudderstacks/Integrations-Compliance-Reliability-b33dcfec5c3d4284b213f55e2071d7be?pvs=4#c9eb53df3ac74c13a6b7d8715f50a8c2))

**<Checklist before moving to ReadyForRelease>**

---

- [ ] Changes tested locally as well as in dev/staging environments.
- [ ] Existing test cases updated for the new feature. 
- [ ] Has the task been checked against the design request questionnaire - [https://www.notion.so/rudderstacks/When-to-ask-for-a-design-review-a3534d5e4f5f4fcb989847ca9cd96189](https://www.notion.so/rudderstacks/When-to-ask-for-a-design-review-a3534d5e4f5f4fcb989847ca9cd96189)

---

- [ ] The Slack link for the respective thread is attached.
- [ ] Docs card attached.
- [ ] GitHub PR is attached to the task.
- [ ] Release label attached to the task.
- [ ] The project associated with the task is linked, if any. 
- [ ] Document the monitoring steps here

---

@gbardis said:

> Hello,
>
> There is github issue raised in js sdk repo for FB pixel integration, [https://github.com/rudderlabs/rudder-sdk-js/issues/1597](https://github.com/rudderlabs/rudder-sdk-js/issues/1597). Can someone please pick it up with the customer?
>
> [\#1597 BUG : Category is used incorrectly as ContentType for FB Pixel](https://github.com/rudderlabs/rudder-sdk-js/issues/1597)

**Comment by nfiacco** [comment]
<img width="829" alt="image" src="https://github.com/rudderlabs/rudder-sdk-js/assets/9993537/6375333c-59c4-41d1-b502-99a98bd2066a">

You can see that `category` is also used as `content_category`. This prevents us from effectively using the Rudderstack `category` property to map contentType.

**Comment by MoumitaM** [comment]
Hi @nfiacco,
Apologies for the delayed response. We will look into it.

**Comment by sandeepdsvs** [comment]
Thank you @nfiacco for bringing this to our attention. 
As this represents a breaking change that will impact multiple users, we are conducting a thorough impact analysis to address it appropriately. We will notify you once we have resolved the issue.
Thank you for your patience.

**Comment by sandeepdsvs** [comment]
Hey @nfiacco, as you identified the two fields, `category` and `content_type` are not contextually related and cannot be used for mapping each other. Ideally `content_type` should be provided in the event payload as part of properties and cannot be populated using some mapping field.
We will add the support for getting `content_type` from event properties and will set it in the destination.
We will remove the category to content type mapping field from UI, but the mapping values, if already set, will be used as fallback if the content_type cannot be found in message properties.
