### ISSUE TITLE
Feature Request: Add SHA256 Email hashing for Criteo

### ISSUE THREAD

**Issue by pierreavizou** [rudderlabs/rudder-sdk-js#1612]
**Is your feature request related to a problem? Please describe.**
Criteo have recently published new guidelines for their OneTag implementation, in preparation for the end of third-party cookies support. 

Among these guidelines is the requirement to use SHA256 hashing for emails. This needs to be done in addition to the MD5 hashing, to maximize correspondence in their identity graph.

**Describe the solution you'd like**
Add SHA256 hashing to the Criteo integration. 
This should consist of adding one line of code for SHA256 in addition to the existing one for MD5, like below: 

```javascript
{ event: "setEmail", email: "##SHA256-hashed Email Address of User##", hash_method: "sha256" }, // Add this
{ event: "setEmail", email: "##MD5-hashed Email Address of User##", hash_method: "md5" },
```

**Comment by koladilip** [comment]
Thanks for creating this change, can you share a public documentation link where this is documented?

**Comment by pierreavizou** [comment]
Sure, you can find documentation here, it show tag implementation with both sha256 and md5 emails: https://help.criteo.com/kb/guide/en/intro-to-the-criteo-onetag-8fjCDwCENw/Steps/775595,853887,2616497,2616569,2616738,2617588
