### ISSUE TITLE
BUG : Safari cancels XHR requests when navigating away from domain

### ISSUE THREAD

**Issue by jinglybits** [rudderlabs/rudder-sdk-js#1614]
**Describe the bug**
If you have an outbound link and track an event via onClick, safari will cancel the request and the event will not be tracked in rudderstack.

**To Reproduce**
```
<button onClick={() => {
  window.rudderstackanalytics.track('test_event');
  window.location.href = "http://google.com"
}>
  Crikey
</button>
```

**Expected behavior**
It should ideally track the event. A possible fix could be for the callback to be invoked AFTER the XHR request resolves:
```
<button onClick={() => {
  // this does not work as the callback is invoked before XHR resolves
  window.rudderstackanalytics.track('test_event', () => {
    window.location.href = "http://google.com"
  })}
>
  Crikey
</button>
```

**Additional info**
Note: if `useBeacon` is set to true, events seem to track. Took awhile to figure this out, so perhaps if this not fixed, it could be documented that `useBeacon` should be enabled to fix safari.

**Comment by MoumitaM** [comment]
Hi @jinglybits,
Thank you for raising your concern. Yes, it is true when you navigate away from a page as soon as an event has been triggered, there might be scenarios where the browser cancels the request. It is not only for Safari, it might happen in other browsers also.
That is why we have this feature: https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-javascript-sdk/supported-api/#querystring-api
In case of beacon, it is different, the browser maintains the queue to send the data to the server. Whenever it detects the tab is closed it immediately flushes the data.
This is a known scenario.
