### ISSUE TITLE
BUG: Vite struggles with package due to configuration

### ISSUE THREAD

**Issue by lukebowerman** [rudderlabs/rudder-sdk-js#1623]
**Describe the bug**

Managed to workaround this issue (manually marked package as ESM) but would love it the issues identified here: https://publint.dev/@rudderstack/analytics-js@3.0.0-beta.22 were addressed so this would "just work" with vite builds. :)

**To Reproduce**

Visit the report at: https://publint.dev/@rudderstack/analytics-js@3.0.0-beta.22

**Additional Information (please complete the following information):**

- SDK installation: NPM/CDN
- CDN URL: (if applicable)
- NPM Version: 3.0.0-beta.22
- Share the event payload
- Used JS Framework (e.g: Remix + vite)

**Comment by bardisg** [comment]
Hello @lukebowerman, 

Thank you for raising this. 
We will look into it and provide a fix soon.

Could you also please provide the error you were getting as our react vite example in the repo did not get any issues bundling current package and we would like to investigate in depth such issues.

Would we be able to replicate just with vite remix boilerplate?

**Comment by MoumitaM** [comment]
Closing this as we didn't receive any further clarification about the bug.

**Comment by lukebowerman** [comment]
Hi - @bardisg / @MoumitaM – I apologize for dropping the ball here. Got swamped with other things and never made it back to putting together a reproduction. 

I went ahead and created a bare-bones Remix+Vite app with Rudderstack to show the issue. The repo is at https://github.com/lukebowerman/vite-remix-rudderstack-repro

To reproduce:

```
clone repo
npm install
npm run dev
```

You should see the following output when attempting to visit the application:

<img width="1258" alt="image" src="https://github.com/rudderlabs/rudder-sdk-js/assets/19156294/87044ad5-31cb-44af-8aa3-db6ef2f3ae68">

The workaround is to add the package to the Vite config with `ssr.noExternal` but more ideally the `package.json` in your upstream package would be fixed to include `"type": "module"`

You can see the publint's recommendations at: https://publint.dev/@rudderstack/analytics-js@3.1.1
