### ISSUE TITLE
BUG : crypto.js discontinued

### ISSUE THREAD

**Issue by ranganathkoman** [rudderlabs/rudder-sdk-js#1631]
**Describe the bug**
The [crypto.js](https://www.npmjs.com/package/crypto-js) library being used in this repository has been discontinued. 

**Additional Information (please complete the following information):**

- SDK installation: 3.0.0-beta.27
- CDN URL: (if applicable)
- NPM Version: (if applicable)
- Webpage URL: (where the SDK is installed, if applicable)
- Share the event payload
- Integration that has the issue (if applicable)
- Used JS Framework (e.g: NextJS, ReactJs, Vue) (if applicable)

**Comment by MoumitaM** [comment]
Hi @ranganathkoman , 
Thank you for raising your concern, however, I do not think this is a bug.
In v3 JS SDK, we have already moved ahead from this dependency. It is still there for the legacy SDK(v1.1) and migration purposes.
Let me know you have any other concerns.

**Comment by ranganathkoman** [comment]
But this library seems to be in the latest version as well?
[](https://github.com/rudderlabs/rudder-sdk-js/blob/develop/package.json)

**Comment by MoumitaM** [comment]
This is a monorepo, if any of the packages use any dependency, it should also be listed in the root level package.json.
