### ISSUE TITLE
BUG : a.push is not a function

### ISSUE THREAD

**Issue by Brumor** [rudderlabs/rudder-sdk-js#1671]
**Describe the bug**
When calling load using SDK v3 (`@rudderstack/analytics-js/bundled`), I get the following error: `a.push is not a function`

**To Reproduce**

I followed the steps indicated here: https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-javascript-sdk/v3/#using-npm

Here is the code:

```ts
import type { ApiObject } from "@rudderstack/analytics-js/bundled";
import { RudderAnalytics } from "@rudderstack/analytics-js/bundled";

const rudderanalytics = new RudderAnalytics();

export const initRudderstack = (startSession = false) => {
  const dataPlaneUrl = getRudderstackDataPlaneUrl();
  const writeKey = getRudderstackKey();
  if (!writeKey || !dataPlaneUrl) {
    return console.error("Couldn't find a rudderstack Key or Url");
  }
  rudderanalytics.load(writeKey, dataPlaneUrl, {
    sessions: { autoTrack: startSession },
  });

  return new Promise<void>((res) => rudderanalytics.ready(res));
};

export const startRudderstackSession = () => {
  rudderanalytics.startSession();
  return rudderanalytics.endSession;
};

export const trackRudderStackEvent = (
  eventId: string,
  properties: ApiObject
) => rudderanalytics.track(eventId, properties);

export const getRudderStackAnonymousId = () => rudderanalytics.getAnonymousId();

export const getRudderStackSessionId = () => rudderanalytics.getSessionId();

```

**Expected behavior**
Not get an error message & events get sent.

**Screenshots**

![image](https://github.com/rudderlabs/rudder-sdk-js/assets/19175088/563afc55-9cfa-4f94-b73d-cc04433613ae)
![Screenshot 2024-03-22 at 10 06 43](https://github.com/rudderlabs/rudder-sdk-js/assets/19175088/3c3da0fb-e90b-4302-974d-772b9fe2cdba)
![Screenshot 2024-03-22 at 10 06 18](https://github.com/rudderlabs/rudder-sdk-js/assets/19175088/2535676a-3083-419d-b11c-e025b133cf0b)

**Additional Information (please complete the following information):**

- SDK installation: NPM
- NPM Version: 3.0.1
- Used JS Framework: ReactJs, although I try to keep the implementation vanilla

**Desktop (please complete the following information):**

- OS: macOS
- Browser edge
- Version 122

**Additional context**
- originally tried with the legacy package, but it was sending a page event without any way to turn it off, so I decided to test the new one
- I got another issue with the normal one, then read about using the bundled version so I did that and now I am running into this issue instead.

It seems like it's trying to push to `window.rudderanalytics`, but that's an object:

![Screenshot 2024-03-22 at 10 17 34](https://github.com/rudderlabs/rudder-sdk-js/assets/19175088/f826372f-7a4e-40df-9ed5-750acbc9b482)
![Screenshot 2024-03-22 at 10 17 51](https://github.com/rudderlabs/rudder-sdk-js/assets/19175088/d5030e0c-97d7-4bf4-a3fd-c45192ab5a33)

**Comment by MoumitaM** [comment]
Hi @Brumor, 
Thank you for raising this. I will check it out.

**Comment by MoumitaM** [comment]
Can you clarify if you are using npm or cdn?
If you are using npm then why do you have the loading script?

**Comment by Brumor** [comment]
I am using npm, I don't know how the loading script gets added

**Comment by Brumor** [comment]
Indeed, one of the MFE we are loading into our app seems to be adding that script, this would be an issue on our side then, thanks for the help!
