### ISSUE TITLE
bug: MutationObserver is not defined

### ISSUE THREAD

**Issue by DanielSinclair** [rudderlabs/rudder-sdk-js#1678]
**Describe the bug**
Seeing an error log fired within the Next.js Page Router server when rendering pages with the `RudderAnalytics` SDK loaded.

> event - compiled client and server successfully in 387 ms (1045 modules)
 RS SDK  CapabilitiesManager:: MutationObserver is not defined

**To Reproduce**

1. Install `@rudderstack/analytics-js` at `3.0.3`
2. Load pages router page with `RudderAnalytics` loaded
3. See server error

**Additional Information (please complete the following information):**

- SDK installation: NPM
- NPM Version: `3.0.3`
- Used JS Framework: Next.js `^12.2.3` with Page Router

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version 123

**Comment by saikumarrs** [comment]
Hello @DanielSinclair,
Here is a working Next.js page router sample application: https://github.com/rudderlabs/rudder-sdk-js/tree/develop/examples/nextjs/page-router/sample-app.

What is the TypeScript version and bundling framework you use?

**Comment by DanielSinclair** [comment]
@saikumarrs TypeScript v4.7.4 and the standard next bundler.

**Comment by DanielSinclair** [comment]
That example looks to be on Next 13. We're using the Pages Router on Next 12.2.3 when seeing this console error.

**Comment by saikumarrs** [comment]
Hi @DanielSinclair,
`MutationObserver` is defined in all modern browsers. I don't see a reason why it fails for your use case. By any chance, is the RudderStack SDK loaded in a non-browser environment? If that's the case, I assume you will see a lot more errors along with it.

The example application I shared also uses TypeScript v5.
Can you try it and let me know if you face any issues?

**Comment by saikumarrs** [comment]
Hello @DanielSinclair
We realized that the `MutationObserver` polyfill is not needed anymore and removed it. Your issue will be automatically addressed in the next release.
Thank you for bringing this to our notice.

**Comment by DanielSinclair** [comment]
Thank you!
