### ISSUE TITLE
BUG: Chrome warnings for Third-party Cookie usage

### ISSUE THREAD

**Issue by DanielSinclair** [rudderlabs/rudder-sdk-js#1689]
**Describe the bug**
We are seeing console warnings related to Rudderstack's usage of third-party cookies in our Chrome Extension as a result of Chrome's upcoming third-party cookie deprecation described here: https://developers.google.com/privacy-sandbox/3pcd

<img width="492" alt="Screenshot 2024-04-12 at 2 35 13 AM" src="https://github.com/rudderlabs/rudder-sdk-js/assets/4412473/1052e8da-c7d7-4f42-a7d9-249f9aefd974">

**To Reproduce**
1. Initiate Rudderstack in Chrome extension
2. Find console warnings in DevTools

**Expected behavior**
Remove reliance on third-party cookies.

**Additional Information (please complete the following information):**

- SDK installation: NPM
- NPM Version: `3.0.3`
- Used JS Framework: Next.js `^12.2.3` with Page Router

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version 123

**Comment by saikumarrs** [comment]
Hello @DanielSinclair
By default, SDK creates all its cookies as a first party, i.e., on your site's top-level domain.
Have you configured any load API options to customize the cookies` behavior in the SDK?

Also, are any device mode destinations connected to your JS source? They may create some third-party cookies.

**Comment by saikumarrs** [comment]
Also, BTW our service worker package is suitable for usage in browser extensions,
https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-javascript-sdk/service-worker/

Can you please double-check if you have used the correct package?

**Comment by DanielSinclair** [comment]
@saikumarrs Nope, no alterations to the load behavior. All of the destinations (Amplitude and S3) are using Cloud Mode to my knowledge. Yes, we are using `@rudderstack/analytics-js-service-worker`.

```ts
this.client = new RudderAnalytics(
  process.env.RUDDERSTACK_WRITE_KEY,
  `${process.env.RUDDERSTACK_DATA_PLANE}/v1/batch`,
);
```
The full implementation is here if you're curious: https://github.com/rainbow-me/browser-extension/blob/297cb04819a78cdf22235d5b9981ab97ae7ee485/src/analytics/index.ts

**Comment by saikumarrs** [comment]
@DanielSinclair, thanks for sharing the details.
I'll get back to you.

**Comment by saikumarrs** [comment]
@DanielSinclair, since we've discussed this on a different communication channel, I'm closing this.
