### ISSUE TITLE
BUG: Vite struggles with package due to configuration (with repro)

### ISSUE THREAD

**Issue by lukebowerman** [rudderlabs/rudder-sdk-js#1757]
Resubmitting this as I commented a while back on the closed ticket but haven't heard back.

---

**Describe the bug**

Managed to workaround this issue (manually marked package as ESM) but would love it the issues identified here: https://publint.dev/@rudderstack/analytics-js@3.0.0-beta.22 were addressed so this would "just work" with vite builds. :)

**To Reproduce**

Visit the report at: https://publint.dev/@rudderstack/analytics-js@3.0.0-beta.22

**Additional Information (please complete the following information):**

- SDK installation: NPM/CDN
- CDN URL: (if applicable)
- NPM Version: 3.0.0-beta.22
- Share the event payload
- Used JS Framework (e.g: Remix + vite) 

-----

I apologize for dropping the ball here. Got swamped with other things and never made it back to putting together a reproduction. 

I went ahead and created a bare-bones Remix+Vite app with Rudderstack to show the issue. The repo is at https://github.com/lukebowerman/vite-remix-rudderstack-repro

To reproduce:

```
clone repo
npm install
npm run dev
```

You should see the following output when attempting to visit the application:

<img width="1258" alt="image" src="https://github.com/rudderlabs/rudder-sdk-js/assets/19156294/87044ad5-31cb-44af-8aa3-db6ef2f3ae68">

The workaround is to add the package to the Vite config with `ssr.noExternal` but more ideally the `package.json` in your upstream package would be fixed to include `"type": "module"`

You can see the publint's recommendations at: https://publint.dev/@rudderstack/analytics-js@3.1.1

_Originally posted by @lukebowerman in https://github.com/rudderlabs/rudder-sdk-js/issues/1623#issuecomment-2132678332_

**Comment by saikumarrs** [comment]
Hello @lukebowerman 
Thanks for raising it. We'll get back to you.

**Comment by saikumarrs** [comment]
Hello @lukebowerman 
Thanks for bringing them to our notice.
We've addressed the issues in the packages. The updated SDK will be released on the upcoming Monday.

**Comment by lukebowerman** [comment]
Thank you!

**Comment by saikumarrs** [comment]
Hello @lukebowerman,
All the reported issues have been addressed in v3.6.1.

Can you please check and confirm?

**Comment by lukebowerman** [comment]
Just tested it out in a staging and production environments and it appears to be working perfectly now. Thank you!
