### ISSUE TITLE
BUG : Add SHA256 Email hashing for Criteo

### ISSUE THREAD

**Issue by pierreavizou** [rudderlabs/rudder-sdk-js#1787]
**Is your feature request related to a problem? Please describe.**
Criteo have recently published new guidelines for their OneTag implementation, in preparation for the end of third-party cookies support. 

Among these guidelines is the requirement to use SHA256 hashing for emails. This needs to be done **in addition** to the MD5 hashing, to maximize correspondence in their identity graph.

Currently, the Rudder SDK only sends **either** the MD5 **or** the SHA256 hashed email. It needs to send **both**.

**Describe the solution you'd like**
Add SHA256 hashing to the Criteo integration. 
This should consist of adding one line of code for SHA256 in addition to the existing one for MD5, like below: 

```javascript
{ event: "setEmail", email: "##SHA256-hashed Email Address of User##", hash_method: "sha256" }, // Add this
{ event: "setEmail", email: "##MD5-hashed Email Address of User##", hash_method: "md5" },
```

You can find documentation here, it show tag implementation with both sha256 and md5 emails: https://help.criteo.com/kb/guide/en/intro-to-the-criteo-onetag-8fjCDwCENw/Steps/775595,853887,2616497,2616569,2616738,2617588

**Comment by ItsSudip** [comment]
Hey @pierreavizou,
I can see they have mentioned this [here](https://help.criteo.com/kb/guide/en/criteo-onetag-advanced-settings-M2TiX6m90K/Steps/886908,887075#:~:text=Note%3A%20Criteo%20is,update%20is%20required.).

> Note: Criteo is migrating from hashing our emails via MD5/SHA256MD5 to SHA256. To maximize match rates between your data and our identity graph, especially during the migration period, please share either legacy formats (MD5 or SHA256MD5) alongside the new SHA256 format.
> If you are unable to share both, please prioritize the SHA256 format.
> If you are sharing plain text, no update is required.

So it seems they are asking to send both the hash data for the migration period only. Can you add it by yourself?
