### ISSUE TITLE
BUG : ublock blocking all paths with /beacon/ 

### ISSUE THREAD

**Issue by tak-hntlabs** [rudderlabs/rudder-sdk-js#1869]
**Describe the bug**
I'm using rudderstack JavaScript API for our web app. In testing analytics, I installed ublock as a Chrome extention. ublocks seems to be blocking all paths with the "/beacon/" in it. None of the rudderstack events go through. I have set up our custom domain. Without ublock, rudderstack events are sent fine. But with ublock enabled, the http requests are blocked.

**To Reproduce**

1. Install ublock origin lite Chrome extension
2. Open dev console, open the network tab
3. Go to any site using rudderstack analytics
4. Observe the console logs. Http requests with url like .../beacon/.../batch?writeKey=... are blocked

**Expected behavior**
events are not blocked

**Screenshots**

**Additional Information (please complete the following information):**

- SDK installation type: NPM
- SDK CDN URL: (if applicable)
- SDK version: (for NPM installation)
- Node version: (if applicable)
- NPM version: 3.1.0
- TypeScript version: (if applicable)
- Webpage URL: (where the SDK is installed, if applicable)
- Share the event payload: (if applicable)
- Integration that has the issue: (if applicable)
- Framework and version(e.g: Next.js, React, Vue): react, vite
- Bundling toolset (e.g: Webpack, Rollup): (if applicable)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ricardocosta** [comment]
Hello,

I'm facing the same/similar issue. It seems that, despite having a custom domain configured in Rudderstack, it still tries to download some script from Rudderlabs CDN, which is blocked by uBlock and prevents `track` calls from going through.

<img width="492" alt="image" src="https://github.com/user-attachments/assets/283f206d-b2e4-43fa-8d3c-0fd2b0fd94cc">

**Comment by tak-hntlabs** [comment]
> Hello,
> 
> I'm facing the same/similar issue. It seems that, despite having a custom domain configured in Rudderstack, it still tries to download some script from Rudderlabs CDN, which is blocked by uBlock and prevents `track` calls from going through.
> 
> <img alt="image" width="492" src="https://private-user-images.githubusercontent.com/11922336/372404798-283f206d-b2e4-43fa-8d3c-0fd2b0fd94cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MDY5NjQsIm5iZiI6MTcyNzgwNjY2NCwicGF0aCI6Ii8xMTkyMjMzNi8zNzI0MDQ3OTgtMjgzZjIwNmQtYjJlNC00M2ZhLThkM2MtMGZkMmIwZmQ5NGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE4MTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZWU5OWJmZDAxM2I3MDU4YTNmOTgzYjMwMDY2OGRjNWM0OWRjZGE1YzYzMWNkNTI2OWIyYzFlOTQwYTA5MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HqRcTWip21EpcwX-8X6Wj6g6koLM9VUHhhNHjARXOHM">

You can make this work by adding this option:

```typesscript
 rudder.load(writeKey, dataPlaneUrl, {
                    ...
                    pluginsSDKBaseURL,
                })
```

**Comment by saikumarrs** [comment]
Hello @tak-hntlabs 
Thanks for raising it to us. We're investigating it.

One potential solution is to support an obfuscated alias for the beacon endpoint to make it harder for adblockers to block.
We'll make sure to keep you posted.


Additionally, thanks for clarifying the load API option above. 

@ricardocosta, if you have any device mode destinations connected to your source, you should also exercise the `destSDKBaseURL` [option](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk/#:~:text=to%20session%20tracking.-,destSDKBaseURL,-String).
Please let us know if you need any help.
