### ISSUE TITLE
BUG : `null` values are removed from event properties

### ISSUE THREAD

**Issue by happypoulp** [rudderlabs/rudder-sdk-js#1901]
**Describe the bug**

When sending an event that contains `null` values in its properties, those values gets removed when the SDK sends the event.

**To Reproduce**

1. Send an event that contains `null` in its properties
2. See that in the payload that RS SDK is sending, the properties containing `null` have been removed.

**Expected behavior**

I would expected all non-undefined properties of an event to be sent by the SDK, including "null" ones.

**Screenshots**

Those are screenshots of a step-by-step debugging made in Chrome and showing that the SDK removed a property that was `null`.

![1](https://github.com/user-attachments/assets/295b2873-082e-49c6-8ffb-abb23680238b)
![2](https://github.com/user-attachments/assets/91366ddc-1f33-467e-889f-05d9f8fac807)
![3](https://github.com/user-attachments/assets/796088b2-20ec-4186-8fff-273cd5563185)

Screenshot of the network event payload sent by the SDK, where a property with a "null" value have been removed:
![4](https://github.com/user-attachments/assets/9c65181c-740c-461d-af9b-93cecf0a610a)

**Additional Information (please complete the following information):**

- SDK installation type: NPM
- SDK version: 3.7.15
- Node version: 18.18.0
- NPM version: 9.8.1
- TypeScript version: 5.6.2
- Webpage URL: jobteaser.com
- Share the event payload: (if applicable)
- Integration that has the issue: (if applicable)
- Framework and version(e.g: Next.js, React, Vue): (if applicable)
- Bundling toolset (e.g: Webpack, Rollup): (if applicable)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOs 14.4
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22] 129.0.6668.101

**Additional context**

**Comment by saikumarrs** [comment]
Hello @happypoulp 
This is the expected behaviour of the SDK and it has been ever since. We don't like to propagate null values from the SDK.
Can you please elaborate your use case?

**Comment by happypoulp** [comment]
Our use case is to define in our tracking plan a "required" property but that may not always present and so we declare it as either a `string` or `null`.
So we expect to receive `null` under certain circumstances and we make sure to provide `null` when needed in our codebase, however since the SDK removes `null` properties we end up with a Violation error "Required-Missing".

**Comment by saikumarrs** [comment]
Hello @happypoulp, 
Sorry, I'm a bit confused here. 

If the value in your app is not always present, could it be marked as a required field in the tracking plan?
Please clarify.

**Comment by happypoulp** [comment]
Hello,

Talking with our data team, here was the rationale behind having a "required" property with a possibly `null` value:

We use a "required" property for **important** properties that we **do not want to be missing**, so that developers **have to always pass** that property even if it means passing it with a `null` value sometimes.
If we were to use an "optional" property, a developer could erase a property by mistake and we would never (or very lately) realize that we are missing this property since there would be no violation reported.

So we're declaring important properties using "required" + `["string", "null"]` to enforce the overall quality and control of our events.

**Comment by saikumarrs** [comment]
Hello @happypoulp 
Alternatively, you can send empty string value `` instead of `null`. The validation will also pass in this case.

**Comment by happypoulp** [comment]
Thanks @saikumarrs, that's indeed the direction we're taking 👌 .
