### ISSUE TITLE
BUG : Retry of batched events fails due to unexpected structure of the data

### ISSUE THREAD

**Issue by vitalybaev** [rudderlabs/rudder-sdk-js#1917]
**Describe the bug**
After a failure, events must be retried later and retry request must be performed. But during request preparation (in the `getRequestInfo`) for the first retry turns out that `itemData` argument is not an array of items, but rather an array with an array of items (one unexpected nested level), because of that in the map cycle `.event` property cannot be found and, therefore, in the line:
```js
eventsDelivery.getFinalEventForDeliveryMutator(queueItemData.event, currentTime)
```
`queueItemData.event` is `undefined`, which breaks code execution

We use `XhrQueue`

**To Reproduce**

1. Enable batching during SDK loading
2. Make sure backend returns 5xx for `../v1/batch`
3. Track events, wait until batch flush and retry

**StackBlitz Reproduction Project**
1. Open https://stackblitz.com/edit/stackblitz-starters-sjggdm?file=analytics%2Finit-analytics.ts
2. Put a write-key at `analytics/init-analytics.ts:13`
3. Restart the project (cmd `npm install && npx next dev`)
4. On the running project, click "Track Data"

**Expected behavior**
Retry event is sent.

**Screenshots**
![CleanShot 2024-11-11 at 14 20 14@2x](https://github.com/user-attachments/assets/4fc2aaba-d55f-4ae2-b125-73932892c01f)

**Additional Information (please complete the following information):**

- SDK installation type: NPM
- SDK CDN URL: N/A
- SDK version: 3.10.0 (latest)

**Desktop (please complete the following information):**

- OS: macOS
- Browser Problem is browser independent
- Version Arc 1.67.0, Chromium 130.0

**Comment by vitalybaev** [comment]
Follow-up question: so far, only failures with 429 and 5xx HTTP codes are going to be retried, but we don't want to miss failures due to temporal network issues of the clients, for example.
Is there any way to retry sending in this case (via configuration parameter, for example)?

**Comment by saikumarrs** [comment]
Hello @vitalybaev 
Thanks for bringing this to our attention. We'll investigate it and get back to you.

On your other questions, no, we do not have any configuration override to retry other N/W failure status codes. 
RudderStack-hosted data plane servers have an uptime SLA of 99.95%. So, we don't expect any major issues in this case.

**Comment by vitalybaev** [comment]
@saikumarrs it works well, thanks for such a quick fix!
