### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by helfi92** [rudderlabs/rudder-sdk-js#202]
We are sometimes seeing `Cannot ready property 'get' of undedefined`

<img width="924" alt="Screen Shot 2021-02-03 at 7 28 30 PM" src="https://user-images.githubusercontent.com/3766511/106827035-14602d00-6656-11eb-83cb-8a77974cac80.png">

Is it possbile `this.storage` is not always defined?

**Comment by sayan-mitra** [comment]
How often are you seeing this ?
The SDK currently expects access to cookie or local-storage for persisting data like user information.
We have planned to use in-memory structure down the line if access to above is restricted. It will be nice to know how frequently is this happening.

**Comment by saikumarrs** [comment]
@helfi92 We've updated the SDK to throw an error during the initialization if both the storage resources are unavailable. Therefore, closing this issue.
