### ISSUE TITLE
.ready() only reaches it's callback if .load is called before it

### ISSUE THREAD

**Issue by JulsRicketti** [rudderlabs/rudder-sdk-js#232]
According to the documentation, `analytics.ready()` is called before `.load()` for the initialization:

```javascript
...
rudderanalytics.ready(() => {console.log("we are all set!!!")})
rudderanalytics.load(YOUR_WRITE_KEY, DATA_PLANE_URL)
...
```

This did not work. Although things do seem to load, we would never get to the `we are all set!!!` log.

However, this minor issue would be fixed if the `.load()` and `.ready()` were reversed. So, although the above did not work as expected, the following does:

```javascript
...
rudderanalytics.load(YOUR_WRITE_KEY, DATA_PLANE_URL)
rudderanalytics.ready(() => {console.log("we are all set!!!")})
...
```

Is this a documentation error?

Also, follow up to all of this. For practical purposes, the other calls seem to work fine with or without the `.ready()`, so I was wondering what is its purpose exactly and if it is required to get the sdk working as expected.

Thanks!

**Comment by sayan-mitra** [comment]
sorry for this. Yes, this requires a doc update. We will address it.
the ready api in general is not required for event tracking. It is useful in cases where for ex: you would need to get the SDK generated anonymousId using `getAnonymousId()` call. Another use-case is to get the native SDKs global object after Rudder SDK has pulled their SDK and they are ready to accept events. The ready callback is called once the SDK has finished loading and also has pulled in other native SDKs (device-mode destinations) and successfully loaded them on the page.

**Comment by saikumarrs** [comment]
Documentation is updated to match the SDK behavior.
