### ISSUE TITLE
Event name in page call in Customer.io is too long

### ISSUE THREAD

**Issue by mderazon** [rudderlabs/rudder-sdk-js#249]
Getting these errors from Customer.io:
> event name cannot be longer than 100 bytes

With this (example) payload
```json
{
  "data": {
    "initial_referrer": "$direct",
    "initial_referring_domain": "",
    "path": "/help/creating-a-google-calendar-account-that-uses-your-business-email-address",
    "referrer": "$direct",
    "referring_domain": "",
    "search": "",
    "tab_url": "https://help.oncehub.com/help/creating-a-google-calendar-account-that-uses-your-business-email-address",
    "title": "Creating a Google Calendar account that uses your business email address | OnceHub",
    "url": "https://help.oncehub.com/help/creating-a-google-calendar-account-that-uses-your-business-email-address"
  },
  "name": "https://help.oncehub.com/help/creating-a-google-calendar-account-that-uses-your-business-email-address",
  "timestamp": 1621642003,
  "type": "page"
}
```

Customer.io does not natively support a page call, so it's being sent as a regular event with the `name` as the page url.
Page url can easily exceed 100 bytes.

Maybe it's better to use a constant name for the event and send the page url as a prop

Happy to provide a PR if you can suggest the desired solution

**Comment by saikumarrs** [comment]
@mderazon Thanks for raising the issue. We'd be happy to review the updates if you can raise the PR.

**Comment by mderazon** [comment]
Hey @saikumarrs have been out of touch with this issue for some time, please let me check it again and get back to you

**Comment by saikumarrs** [comment]
@mderazon This issue has been addressed in the cloud mode integration. A gentle reminder to raise a PR to fix this issue here.

**Comment by shrouti1507** [comment]
Hi, @mderazon, we tried to reproduce this issue via web-device mode and sent page events with the exact URL provided in the example. We did not face any problems with this. Can you check once again?

We sent the following call to test:
```
  rudderanalytics.page("category", "https://help.oncehub.com/help/creating-a-google-calendar-account-that-uses-your-business-email-address", {
  path: "test-path",
  url: "https://help.oncehub.com/help/creating-a-google-calendar-account-that-uses-your-business-email-address",
  title: "title",
  search: "search",
  referrer: "https://help.oncehub.com/help/creating-a-google-calendar-account-that-uses-your-business-email-address",
});
```
And received output in customerIO dashboard.

<img width="1177" alt="Screenshot 2022-09-29 at 12 15 28 PM" src="https://user-images.githubusercontent.com/60211312/192958755-56828971-99b1-4f39-bbe4-3cbad8cd2da8.png">

**Comment by shrouti1507** [comment]
closing this as no correspondence received
