### ISSUE TITLE
Add TypeScript support for RS specifications (e.g. ecommerce)

### ISSUE THREAD

**Issue by alan-cooney** [rudderlabs/rudder-sdk-js#275]
This project seems like the perfect use case for TypeScript because:

- Most of the integrations code involves converting RS specification properties into destination-specific properties. Currently there is a huge risk of miss-spelling property names on either side of this conversion which TypeScript could mitigate.
- It would be beneficial to TypeScript users if the properties were typed for standard RS events, reducing the risk during implementation as well.
- Because it is safer, it is significantly faster to write/improve than pure JavaScript when dealing with complex objects as this project does.
- Even for non-TS users, most code editors (e.g. VS Code) will use the types to display code hints.

Incremental adaptation would be very straight-forward (i.e. it can just be one file at a time, as they are being edited).

What do you think about incrementally adding it in?

**Comment by saikumarrs** [comment]
@alan-cooney Thanks for all your suggestions. As this is not really an issue in the SDK, we'll track this internally and close this one.
