### ISSUE TITLE
TypeScript definitions are missing from NPM package

### ISSUE THREAD

**Issue by hmhealey** [rudderlabs/rudder-sdk-js#328]
In 1.0.17 and 1.0.18, some files seem to be missing from the package, including the TypeScript definitions. Both of those versions only include `index.js` and `package.json` while previous versions also include `index.d.ts`, `index.html`, and `README.md` as well.

**Comment by saikumarrs** [comment]
@hmhealey Thanks for reporting the issue. Latest package v1.0.19 published to NPM.

**Comment by hmhealey** [comment]
Yep, that fixed it for me. Thanks!
