### ISSUE TITLE
Details about autotrack

### ISSUE THREAD

**Issue by alexkreidler** [rudderlabs/rudder-sdk-js#359]
Hi,

Thanks for a really cool project!

I noticed the README has a note that says you removed autotrack, and links to another repo that has it.

The PR was #231, but it doesn't explain why. It seems like others are a bit confused as well, like https://github.com/rudderlabs/rudder-sdk-js-autotrack/issues/1. 

Was there a main reason for doing so: eg privacy concerns, difficulty maintaining/testing it, that the data was too messy to be useful for most destinations, or that there are other implementations?

The Posthog plugin supports autotrack through its' SDK:
https://github.com/rudderlabs/rudder-sdk-js/blob/01b133b98a73885766487de89720a2035045fd44/integrations/Posthog/browser.js#L10

Do you have plans to add it for other sources that support it through their SDKs, like Heap?

I appreciate any insight you can share. Thanks!

**Comment by saikumarrs** [comment]
Hi @alexkreidler,
We've long deprecated autotrack feature in the SDK as we don't want to pursue it further and the other repository was spinned off just to support existing users.
At this point, we do not have any plans to support auto tracking for other plugins.
Thanks for sharing your thoughts on it.
