### ISSUE TITLE
Using Custom CNAME for Rudderstack URLs

### ISSUE THREAD

**Issue by svjacob** [rudderlabs/rudder-sdk-js#433]
Hello!

I was following the guide laid out by rudderstack to modify the 3 urls needed to run RudderStack Javascript SDK and send events to my own domain.

https://rudderstack.com/docs/user-guides/how-to-guides/custom-domains/

I was able to swap in the dataplane url into the rudderanalytics.load(); call.

However it's not clear where I can put the api.domain.com and cdn.domain.com URL into this package. 

(I have a guess that the exported API functions are from whatever would be loaded from the CDN, but I do see an api.rudderstack.com call being made on our frontend)

Any guidance on this?

Steven

**Comment by MoumitaM** [comment]
Hi Steven,

Thank you for your query. 

As per my understanding, you have already replaced the data plane URL with your own server URL where the events will be delivered. Now you want know where you can put the other two URLs:
1. cdn.domain.com
2. api.domain.com

[Here](https://rudderstack.com/docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/quick-start-guide/#minified-code) you will find how to load the JS SDK. 
In the above snippet, you need to replace our latest SDK URL - `https://cdn.rudderlabs.com/v1.1/rudder-analytics.min.js` with your domain URL(cdn.domain.com) from where the SDK will load.

To understand where to put the second URL you need to look into this [document](https://rudderstack.com/docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/#loading-the-sdk-for-self-hosted-control-plane).
`rudderanalytics.load()` call takes multiple optional parameters. Replace the `CONTROL_PLANE_URL` with your `api.domain.com` in the example given in the document.

Let me know if you need further clarifications.

**Comment by svjacob** [comment]
Hello MoumitaM,

Thanks for your response! I was able to add the desired custom domain for the Control Plane to the options parameters. :)

However for the cdn, I am using this npm package we are currently commenting on, rudder-sdk-js, as far as I can tell we don't have the JS SDK loaded via a script on the html of our website. And that it is somehow being loaded via the NPM package directly? As the guide you sent says that NPM installation is an alternative: "Alternative installation using NPM" (heading).

I technically don't even see any network requests on our website: https://learn.rumie.org, for the rudderstack cdn. So I'm unaware if I need to even worry about replacing this with our CNAME domain url at all.

Thoughts?

Thanks,
Steven

**Comment by MoumitaM** [comment]
Hey Steven,

Yes, you are right, if you are using the NPM package then no need to put your domain URL anywhere. NPM package itself is the JS SDK. So when you will import the package it will do the job.

Thanks,
Moumita

**Comment by MoumitaM** [comment]
Closing this issue since no more queries.
