### ISSUE TITLE
Traits not sent correctly in the Identify call

### ISSUE THREAD

**Issue by fbjork** [rudderlabs/rudder-sdk-js#439]
When sending Identify calls we're seeing the "traits" key nested under "context" rather than at the top level. This isn't according to spec. Is anyone else seeing this?

**Comment by MoumitaM** [comment]
Hey @fbjork,

Thank you for bringing this up.
According to our implementation `traits` should be nested under `context`. May I know which spec file you are referring to?

**Comment by fbjork** [comment]
> Hey @fbjork,
> 
> 
> 
> Thank you for bringing this up.
> 
> According to our implementation `traits` should be nested under `context`. May I know which spec file you are referring to?

https://segment.com/docs/connections/spec/identify/
