### ISSUE TITLE
Not compatible with IE11

### ISSUE THREAD

**Issue by hayden-accurx** [rudderlabs/rudder-sdk-js#446]
The SDK hasn't been compatible with IE11 since v1.2.8.

v1.2.9 onwards will cause an exception preventing the page from loading.

The RudderStack team have confirmed they are working on a fix (thank you), just posting here in-case anyone else is experiencing the issue 🙂

**Comment by MoumitaM** [comment]
Hi @hayden-accurx,

Please check out the latest version. IE support has been added there.

**Comment by saikumarrs** [comment]
The changes have been incorporated in PR #449
