### ISSUE TITLE
ack timestamps in localStorage updated every second

### ISSUE THREAD

**Issue by hmhealey** [rudderlabs/rudder-sdk-js#456]
Is it expected that the values stored in localStorage with the keys `rudder.<some ID>.ack` are updated every second? I'm wondering if this is normal to see or if there might be something we might've done wrong since it seems like that could cause issues if we have, for example, code that's listening for changes in localStorage.

Here's a video of what this looks like in the Firefox dev tools. When I recorded this, we weren't sending any data to Rudder, and there didn't appear to be any requests to it pending.

https://user-images.githubusercontent.com/3277310/154104630-0736e8e9-4f55-4764-9e71-77e64e234b0d.mov

**Comment by MoumitaM** [comment]
Hi @hmhealey, 

Thank you for raising this question. Yes, it is expected behavior. It is internally used by a package for the retry mechanism.

**Comment by hmhealey** [comment]
Thanks! Glad to know it's expected and not a caused by any of our other code that uses storage
