### ISSUE TITLE
IP Address Not Populating

### ISSUE THREAD

**Issue by hcatlin** [rudderlabs/rudder-sdk-js#464]
I've noticed in our Rudderstack Javascript SDK Implementation, neither track() nor page() events are sending the IP address of the client.

Is there a way to resolve that?

**Comment by MoumitaM** [comment]
Hi @hcatlin,

Is there any specific use case when you are not getting IP address? Are you getting it for identify() or other call apart from track and page?

**Comment by hcatlin** [comment]
Not getting it for anything at all!

**Comment by saikumarrs** [comment]
@hcatlin RudderStack JavaScript SDK does not capture the IP address of the client. If you explicitly specify the IP address in the event, RudderStack will use that address instead of capturing it in the backend at `context.ip`.
