### ISSUE TITLE
getUserId not defined in typescript declaration

### ISSUE THREAD

**Issue by haydenjbyrne** [rudderlabs/rudder-sdk-js#472]
The getUserId method, which was recently added, is not defined in [index.d.ts](https://github.com/rudderlabs/rudder-sdk-js/blob/production/dist/rudder-sdk-js/index.d.ts), so is causing an error when I try to access it from a typescript project. Can it be added please?

**Comment by hayden-accurx** [comment]
Thanks for the speedy response, can confirm it's working for me now :)
