### ISSUE TITLE
BUG : fbq is not defined when using the Load

### ISSUE THREAD

**Issue by jkruse00** [rudderlabs/rudder-sdk-js#499]
**Describe the bug**
When using the `load` function we get: 

```js
Uncaught ReferenceError: fbq is not defined
    at <anonymous>:1:1
    at gtm.js?id=GTM-WN2J6:456:414
    at b (gtm.js?id=GTM-WN2J6:457:337)
    at se (gtm.js?id=GTM-WN2J6:91:769)
    at e (gtm.js?id=GTM-WN2J6:215:34)
    at gtm.js?id=GTM-WN2J6:41:130
    at Array.<anonymous> (gtm.js?id=GTM-WN2J6:216:454)
    at Object.execute (gtm.js?id=GTM-WN2J6:216:194)
    at zs (gtm.js?id=GTM-WN2J6:313:1124)
    at Is (gtm.js?id=GTM-WN2J6:318:20)
```

**To Reproduce**
```js 
const initRudderstack = (account, user) => {
    const utm_data = {...};

    const identifyData = {...};

    rudderanalytics.load(rsConfig.key, rsConfig.url);
    rudderanalytics.identify(user.email, identifyData);
};

initRudderstack(account, user); 
```

**Expected behavior**
no error thrown

**Additional Information (please complete the following information):**
- SDK installation: NPM
- NPM Version: 2.3.0

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome
 - Version: 100.0.4896.127

**Comment by utsabc** [comment]
@jkruse00 Thanks for raising the issue can you please share what are the destinations connected through this source especially device mode ones

**Comment by jkruse00** [comment]
@utsabc  We are destination is `Google Tag Manager`

**Comment by utsabc** [comment]
Thanks @jkruse00 We are looking into this

**Comment by ItsSudip** [comment]
@jkruse00 Can you share the facebook_pixel implementation on your GTM, with us?

**Comment by jkruse00** [comment]
My marketing team gave me this I hopes its what you need. 
<img width="1753" alt="image" src="https://user-images.githubusercontent.com/85895769/164491336-71bd333d-de95-44bd-b27c-2f6614731d17.png">

**Comment by jkruse00** [comment]
<img width="1589" alt="image (1)" src="https://user-images.githubusercontent.com/85895769/164491506-a1cab513-edb4-43ad-9a52-8ada24b25d1e.png">

**Comment by ItsSudip** [comment]
We have installed facebook pixel in the similar way you guys have installed in GTM. We were not able to reproduce the error. We have some query regarding the implementations. 
1. In the second screenshot above we can see `Rudderstack JS`, what is the content of this tag? 
2. What is inside `Facebook - Global Pixel`?

**Comment by jkruse00** [comment]
Rudderstack Id: 1rAOS5TDzgx9T39bG58kwN5ZUQz
```js
<script> 
rudderanalytics=window.rudderanalytics=[];for(var methods=["load","page","track","identify","alias","group","ready","reset","getAnonymousId","setAnonymousId"],i=0;i<methods.length;i++){var method=methods[i];rudderanalytics[method]=function(a){return function(){rudderanalytics.push([a].concat(Array.prototype.slice.call(arguments)))}}(method)}rudderanalytics.load('1rAOS5TDzgx9T39bG58kwN5ZUQz','https://mailgun-dataplane.rudderstack.com/'),rudderanalytics.page();
</script>
...
<script src="https://cdn.rudderlabs.com/rudder-analytics.min.js"></script>
```

---

Facebook  Id: 2205356299585031
```js
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '2205356299585031');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=2205356299585031&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->

```
--- 
Sorry for the late reply and thanks for any help.

**Comment by ItsSudip** [comment]
You are loading rudderstack through `GTM` and `GTM` is also connected with rudderstack dashboard. It is not the correct way to do it. If you natively load rudderstack JS-SDK, and `GTM` is connected in rudderstack dashboard as a destination with the `javascript` source (which is true in your case), then `GTM` will be automatically loaded by our JS-SDK. You don't need to provide the above rudderstack snippet as a `GTM` tag.
There is another possibility that the Facebook pixel codes which are added through the `GTM` tag are not correct. 
We tried to reproduce this error but were unable to do that. **If you guys still facing the error we can try to solve this over a call.**

**Comment by jkruse00** [comment]
Thanks for your help in this matter. I have passed these instructions to our Marketing team to implement.
