### ISSUE TITLE
LaunchDarkly: support `shared key for anonymous users`

### ISSUE THREAD

**Issue by chandlervdw** [rudderlabs/rudder-sdk-js#569]
### Issue 
The LaunchDarkly integration [forcefully repurposes the autogenerated Rudderstack ID](https://github.com/rudderlabs/rudder-sdk-js/blob/c38529aec8bb890f4f7022ade9d7fe8ed2172b3d/integrations/LaunchDarkly/utils.js#L3) for the `key` that the LaunchDarkly API accepts. This forces you to pass and set a unique ID for every LaunchDarkly user, potentially maxing out your LaunchDarkly plan very quickly.

### Solution
From the [LaunchDarkly Docs](https://docs.launchdarkly.com/home/users/anonymous-users#tracking-anonymous-users-with-a-shared-key)
> You do not always need to uniquely identify your anonymous users. Instead, you can use a shared key.

**This integration should support `options.integrations.LaunchDarkly.key` as an override OR it should support an `anonymousUsersSharedKey` field.**

**Comment by saikumarrs** [comment]
It has been fixed in https://github.com/rudderlabs/rudder-sdk-js/pull/575.
