### ISSUE TITLE
BUG : destSDKBaseURL is missing from loadOptions type

### ISSUE THREAD

**Issue by femaury** [rudderlabs/rudder-sdk-js#621]
**Describe the bug**
When calling the load method and passing a `destSDKBaseURL` in the options, a typescript project will not compile. You can see in `analytics.js` that `options.destSDKBaseURL` is checked for on [line 1000](https://github.com/rudderlabs/rudder-sdk-js/blob/40ae37aae3ebff9e42ffc1f37ff48a1b71256b5d/analytics.js#L1000)

**To Reproduce**
1. Create a TS project
2. Initialize rudderanalytics by calling the load method and pass in the options object a string for destSDKBaseURL.
3. The project won't compile.

**Expected behavior**
To have the typing defined in `/dist/rudder-sdk-js/index.d.ts`, line 68.

**Screenshots**
<img width="573" alt="Screenshot 2022-08-23 at 12 20 36" src="https://user-images.githubusercontent.com/38667297/186134450-2b0972c9-2b69-4811-8697-c2c00a8ee15b.png">

**Additional Information (please complete the following information):**
- SDK installation: NPM
- NPM Version: 2.11.1

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
I haven't checked if other properties are missing, might be worth doing so :)

**Comment by MoumitaM** [comment]
Hi @femaury, Thank you for bringing this to our notice, we will fix and update you.
