### ISSUE TITLE
BUG : Permission denied to access property "message"

### ISSUE THREAD

**Issue by liby** [rudderlabs/rudder-sdk-js#666]
**Describe the bug**
Permission denied to access property "message"

**To Reproduce**
1. Upgrade rudder-sdk-js from `v2.12.2` to `v2.13.0`.
2. Saw `Permission denied to access property "message"` error on Sentry.

**Expected behavior**
It works.

**Screenshots**
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/38807139/192410641-02fb0f7e-60aa-47b9-9c0d-0bfecfdbb23c.png">

**Additional Information (please complete the following information):**
- SDK installation: NPM
- CDN URL: n/a
- NPM Version: 2.13.0
- Webpage URL: n/a

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.15、Windows 10
 - Browser: Firefox 91.0、Firefox 103.0、Firefox 104.0、Firefox 105.0
 - Version: n/a

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Additional context**

The last working version is  `2.12.2`, so the issue is most likely caused by [this one change](https://github.com/rudderlabs/rudder-sdk-js/pull/520/files#diff-0dfd09124fcab66fd7973250467f8e1128ff29cfeba6ad71cc5bdf821d063984R142).
<img width="923" alt="image" src="https://user-images.githubusercontent.com/38807139/192412265-cd71bcfe-5960-4245-9879-3153a752262d.png">

**Comment by MoumitaM** [comment]
The issue has been resolved in the latest release `2.16.0`.
