### ISSUE TITLE
BUG : Loading the SDK in Incognito with Block Third-party Access throws DOMException (SecurityError)

### ISSUE THREAD

**Issue by mamsoudi** [rudderlabs/rudder-sdk-js#689]
**Describe the bug**
Hey there,
Recently we became aware of a bug in our app and after digging deep, we've noticed that the initalisation of Rudderstack SDK in our app with certain Security Configurations on latest versions of Chrome in iFrame windows throws `DOMException` (with Code 18 - `SecurityError`).
#447 Seems to be related, however the problem here is that in Incognito with Block Third Party Cookies option turned on, accessing `window.localStorage` in `storejs` throws and uncaught error that halts the initialisation and the rest of the app as well.

Now, while it's understandable that under such circumstances users are made aware that the app may break, but I wondered if it's possible to catch and handle the error and return a more friendly error that can be caught and potentially ignored on higher levels.

Lazy loading (dynamically importing the SDK) gives us more control and allows us to catch the `DOMException` and lets the app proceed but a lot of other apps could potentially face the same issue.

**To Reproduce**
1. Create a simple http server that hosts a simple html and loads an iFrame from a different origin
```
// HTML
<iframe src="{differentOriginURL}" />
```
2. Create another http server to load rudderstack and have it served under a html file
```
// JS
import * as r from 'rudder-sdk-js'
```
4. Have the first server load the second one that import `rudder-sdk-js`
5. Open an Incognito tab on Chrome and turn on `Block third-party cookies`
6. Open the console and you shall see the `DOMException`

> I'll soon add a better/easier way to reproduce this.

**Expected behavior**
The right thing in my opinion to do here given that this is probably caused by `storejs` is to properly handle the exception. Current behaviour causes the entire app to break when we import. Now as mentioned before, dynamically importing the library gives us the opportunity to handle (and ignore) the exception in our app, but it's not a solution to the problem.

**Screenshots**
<img width="723" alt="Screen Shot 2022-10-19 at 13 40 02" src="https://user-images.githubusercontent.com/8385009/196584760-8bc71601-0637-484c-a479-d4157622f1dc.png">

**Additional Information (please complete the following information):**
- SDK installation: NPM
- CDN URL: (if applicable)
- NPM Version: 8.19.2
- Webpage URL: (where the SDK is installed, if applicable)

**Desktop (please complete the following information):**
 - OS: Mac/Windows
 - Browser Chrome
 - Version 106

**Smartphone (please complete the following information):**
 - Device: iPhone/Android Devices
 - OS: iOS/Android
 - Browser Chrome
 - Version Different Versions

**Additional context**

**Comment by MoumitaM** [comment]
@mamsoudi, Thank you for raising this. We will look into it.

**Comment by DevinBarth-Zen** [comment]
Looks like this error originates from one of your package dependencies: https://github.com/jaywcjlove/store.js/blob/master/src/main.js#L1

**Comment by bardisg** [comment]
Hello @rubendinho & @DevinBarth-Zen,

Apologies for the delayed response, we will look into fixing this issue with patch-package and then let the original dependency owner know about it.

**Comment by MoumitaM** [comment]
Hey @mamsoudi @rubendinho @DevinBarth-Zen, We have finally released a fix for this in the latest [release](https://github.com/rudderlabs/rudder-sdk-js/releases/tag/v2.30.0). Please try it out and let us know your feedback.

**Comment by DevinBarth-Zen** [comment]
> Hey @mamsoudi @rubendinho @DevinBarth-Zen, We have finally released a fix for this in the latest [release](https://github.com/rudderlabs/rudder-sdk-js/releases/tag/v2.30.0). Please try it out and let us know your feedback.

That seems to have done the trick! Thanks @MoumitaM
