### ISSUE TITLE
BUG : Added/updated traits are not persisted in subsequent calls

### ISSUE THREAD

**Issue by pierreavizou** [rudderlabs/rudder-sdk-js#697]
**Describe the bug**
User traits added / updated in a page or track call are lost in any subsequent call. 
From[ this doc](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-javascript-sdk/supported-api/#traits), I would infer that you can update the traits of an identified user and have these changes persisted. 

**To Reproduce**
1. Load SDK on a webpage
2. Identify a user with some traits

```js
rudderanalytics.identify("1hKOmRA4el9Zt1WSfVJIVo4GRlm", {
  name: "Alex Keener",
  email: "alex@example.com",
  subscriptionStatus: "subscribed",
  plan: "Silver"
});
```
3. Track an user event and pass updated traits to the context
```js
rudderanalytics.track(
  "Subscription Update", {
    campaign: "Subscribe"
  }, {
    traits: {
      plan: "Gold",
      addOn: true
    }
  }
);
```
4. Track subsequent page / user events normally, e.g: 
```js
rudderanalytics.track('test');
```
5. You can see in the network inspector that for this call, user traits sent to the Rudder server are back to the ones defined in the 'identify' call, updates made by the "Subscription Update" call have been lost.

**Expected behavior**

The traits sent by `rudderanalytics.track('test');` are 
```js
{
	"traits": {
		"email": "alex@example.com",
		"name": "Alex Keener",
		"plan": "Silver",
		"subscriptionStatus": "subscribed"
	}
}
```
but my understanding is that they should be 
```js
{
	"traits": {
		"email": "alex@example.com",
		"name": "Alex Keener",
		"plan": "gold", // This should have been updated
                "addOn": true, // This should have been added
		"subscriptionStatus": "subscribed"
	}
}
```

**Additional Information (please complete the following information):**
- SDK installation: CDN
- CDN URL: https://cdn.rudderlabs.com/v1.1/rudder-analytics.min.js

**Desktop (please complete the following information):**
 - OS: tested on Windows/MacOS/Linux
 - Browser Tested on Firefox/Chrome/Edge
 - Version Latest versions

**Additional context**
I may have misinterpreted the documentation, in which case it could perhaps be clarified.

**Comment by saikumarrs** [comment]
Hi @pierreavizou!

The SDK only persists the user and group traits set in the `identify` and `group` calls, respectively. In the other API calls, you can modify or enrich the persisted traits only for that event.

If you need to add/modify the persisted traits, you can call `identify`/`group` APIs:
```
rudderanalytics.identify({
  newTrait1: "val1",
  newTrait2: "val2",
  existingTrait1: "newVal",
  ...
});
```

I'm closing this issue as it is the expected behavior of the SDK.
