### ISSUE TITLE
Page views are being sent without name

### ISSUE THREAD

**Issue by petersobhi** [rudderlabs/rudder-sdk-js#79]
When using the `page()` function, the `name` parameter doesn't reach the debugger or any of the destinations.

### Here is an example:
**JS Code:**
`window.rudderanalytics.page('category', 'name')`

**Network call:**
```
curl --location --request POST 'DATA_PLANE_URL/v1/page' \
--header 'authority: DATA_PLANE_URL' \
--header 'user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1' \
--header 'authorization: Basic **************************' \
--header 'anonymousid: Y2E3OWM4MjctYTdjYi00ZmEyLWI3NDgtMmNjWTMmNWU3NThk' \
--header 'content-type: application/json' \
--header 'accept: */*' \
--header 'origin: http://localhost:3001' \
--header 'sec-fetch-site: cross-site' \
--header 'sec-fetch-mode: cors' \
--header 'sec-fetch-dest: empty' \
--header 'referer: http://localhost:3001/' \
--header 'accept-language: en-US,en;q=0.9' \
--header 'Content-Type: text/plain' \
--data-raw '{
    "channel": "web",
    "context": {
        "app": {
            "build": "1.0.0",
            "name": "RudderLabs JavaScript SDK",
            "namespace": "com.rudderlabs.javascript",
            "version": "1.1.2"
        },
        "traits": {},
        "library": {
            "name": "RudderLabs JavaScript SDK",
            "version": "1.1.2"
        },
        "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1",
        "locale": "en-US",
        "os": {
            "name": "",
            "version": ""
        },
        "screen": {
            "density": 3
        },
        "page": {
            "path": "/",
            "referrer": "http://localhost:3001/",
            "search": "",
            "title": "Homepage",
            "url": "http://localhost:3001/"
        }
    },
    "type": "page",
    "messageId": "85d635ce-c5a6-4cfd-9826-ceaee7b195e2",
    "originalTimestamp": "2020-06-13T22:43:22.008Z",
    "anonymousId": "ca79c827-a7cb-4fa2-b748-2cc53f5e758d",
    "userId": "",
    "properties": {
        "category": "category",
        "path": "/",
        "referrer": "http://localhost:3001/",
        "search": "",
        "title": "title",
        "url": "http://localhost:3001/"
    },
    "integrations": {
        "All": true
    },
    "name": "name",
    "sentAt": "2020-06-13T22:43:22.008Z"
}'
```

**Source live events screenshot:**
<img width="1005" alt="Screen Shot 2020-06-14 at 1 04 50 AM" src="https://user-images.githubusercontent.com/18689240/84581023-1df20780-addd-11ea-814d-26bb2b608bc1.png">

**Comment by sayan-rudder** [comment]
Hi,

the **name** parameter in the page api gets sent out the top level key in the payload.
in the ex above:
the "name" key.

please let us know which destination are you facing the issue, we will check at our end and get back.

@petersobhi

**Comment by petersobhi** [comment]
@sayan-rudder Amplitude

**Comment by sayan-rudder** [comment]
Got it..
we will add a fix to this asap and let you know

**Comment by sayan-mitra** [comment]
@petersobhi we have fixed the issue.
Are you using the docker setup for Rudder installation?

**Comment by sajalmohanta** [comment]
@petersobhi  It has been fixed .Please find the screenshot below
![Screenshot 2020-07-27 at 11 34 48 PM](https://user-images.githubusercontent.com/9445194/88576404-03a97b80-d063-11ea-83ee-4002afc47476.png)

**Comment by kevinavery** [comment]
Hi @sajalmohanta, was this fixed in a version of `rudder-sdk-js` or `rudder-server`? Is there a release for it? Thanks

**Comment by kevinavery** [comment]
Hi @sayan-mitra, was this fixed in a version of rudder-sdk-js or rudder-server? Is there a release for it? Thanks

**Comment by sajalmohanta** [comment]
@kevinavery  This is fixed in `rudder-transformer` . So, pull the latest. If you are using `docker-image` then please use the latest.

**Comment by kevinavery** [comment]
@sayan-mitra I'm using `rudder-helm` which I believe is configured by default to pull the latest. Is there a way to check the version of `rudder-transformer` on a node?

**Comment by kevinavery** [comment]
@sajalmohanta I wasn't sure if helm was pulling the latest so I recreated the deployment from scratch and page events in Amplitude are still coming in as "pageview" rather than "Viewed `<name>` Page" like Segment. When inspecting the raw events in Amplitude, I can see the following differences:

key | rudder | segment
-- | -- | --
device_model | null | Mac
device_type | null | Mac
display_name | pageview | Viewed `<name>` Page
event_type | pageview | Viewed `<name>` Page
library | http/2.0 | amplitude-js/5.2.2
os | | Chrome 83
os_name | null | Chrome
os_version | null | 83
platform | null | Web
start_version | 1.0.0 | null
version_name | 1.0.0 | null

Note that `<name>` is set in `event_properties.name`

**Comment by sajalmohanta** [comment]
@kevinavery We are looking in it
