### ISSUE TITLE
Issue with typescript and npm moule

### ISSUE THREAD

**Issue by sudheerDev** [rudderlabs/rudder-sdk-js#80]
When i use npm module from https://www.npmjs.com/package/rudder-sdk-js i get this error 

```
 File 'XXX/node_modules/rudder-sdk-js/index.d.ts' is not a module.

import * as rudderanalytics from "rudder-sdk-js"
```

https://github.com/rudderlabs/rudder-sdk-js/blob/b6d9c1baf31c5f6413f85b842b0a46eb176aa01b/dist/rudder-sdk-js/index.d.ts#L1

I think your dist index.d.ts should say

`declare module "rudder-sdk-js" {` 

I could be wrong though. Do you guys think it is my env issue? if not Is there a workaround that you guys know of?

**Comment by sayan-rudder** [comment]
thanks for catching this.
we have pushed the changes. 
please use the version 1.0.4 of rudder-sdk-js module.
please let us know if this solves it.

**Comment by sudheerDev** [comment]
Yup, Just checked and it works. Thanks for the quick turnaround on this
