### ISSUE TITLE
BUG : LaunchDarkly Integration now fails with "No user specified"

### ISSUE THREAD

**Issue by sallytraynham** [rudderlabs/rudder-sdk-js#818]
**Describe the bug**
While testing our next release, we noticed that our integration with LaunchDarkly via Rudderstack had recently started failing with `No user specified.` 

It had been previously working and after doing some digging, it looks like recently there was an update to [the file](https://github.com/rudderlabs/rudder-sdk-js/blob/production-staging/src/integrations/LaunchDarkly/browser.js#L48) which changed the logic.
The [previous version](https://github.com/rudderlabs/rudder-sdk-js/blame/1be56798ada52b8e6ba7de6cdbef6e0e9dab56e8/integrations/LaunchDarkly/browser.js#L69) uses `this.launchDarklyUser` instead of `window.user` which is never set.

I'm happy to submit a PR if this would help, but unsure what branch to use as the base. Thanks!

**Expected behavior**
LaunchDarkly should initialize with `this.launchDarklyUser`. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4604160/210293652-b4e606dd-1b9e-41e7-ad27-f58f10ff65bf.png)

**Comment by Gauravudia** [comment]
@sallytraynham  Changes are released. Closing this PR

**Comment by Gauravudia** [comment]
@sallytraynham Changes are released. Closing this issue.
