### ISSUE TITLE
Feature Request: Allow passing destinations ids as keys to the integrations object

### ISSUE THREAD

**Issue by fev4** [rudderlabs/rudder-sdk-js#819]
**Is your feature request related to a problem? Please describe.**

We have two Mailchimp lists and a form where users fill their email along with two checkboxes, one to whether to accept or reject receiving marketing emails, and another to whether be part or not of the beta program (these are the two Mailchimp lists).

These checkboxes are considered application logic, and we are not interested in tracking the interaction events generated from these two checkboxes, **we just want to use the application logic to select which destinations to send events to.**

To be precise, we want to use the logic from these two checkboxes to conditionally send information to the two Mailchimp destinations described earlier.

Currently this is not possible because the `integrations` object only accepts service names, like this:

```javascript
"integrations": {
  "All": true,
  "MailChimp": false
}
```

Meaning that we send to both lists at the same time or not, and it's not possible to only target one Mailchimp destination.

The transformation feature is not helpful in this case either because it's not well-suited to use application logic such as the checkboxes from the form, which again we're not interested in tracking their interactions.

In this sense this is currently not possible within Rudderstack ecosystem, or at least not that I'm aware of.

**Describe the solution you'd like**

If we can use destinations ids as keys for the integrations object we then would have complete control over the destinations where we send events to:

```javascript
"integrations": {
  "All": true,
  "2H675CM69DsI3E2MEwy6t3GvDYj": false,
  "2Jp3150FUtJyyZXuV46Vet3GlMa": true
}
```

**Describe alternatives you've considered**

I considered using Transformers but as mentioned earlier, it's not well-suited to use application logic such as the checkboxes from the form in there.

**Additional context**

I'm using the cloud mode for the JS SDK, on the web, where we have the form. The problem is just an example, but it applies to many other situations where we use more than one destination from the same service.

I've also brought this up as a [Slack question in the support channel](https://rudderstack.slack.com/archives/C01E4PLB135/p1672763352565079).

**Comment by sigginjals** [comment]
This would be pretty cool, I'm running multiple GA4 destinations receiving events from the sam source and I would like to be able to filter which destinations the events are sent to. Right now this is not possible when running in device/hybrid mode(cloud mode allows transformations).
