### ISSUE TITLE
Feature Request: Osano consent manager integration

### ISSUE THREAD

**Issue by ecasilla** [rudderlabs/rudder-sdk-js#941]
**Is your feature request related to a problem? Please describe.**
I would like to enable more consent managers into the sdk to simplify consent management. One trust is nice but way over priced we need more valued based providers.

**Describe the solution you'd like**
Create a new consent integration with osano

**Describe alternatives you've considered**
https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-javascript-sdk/onetrust-consent-manager/#consent-management-with-other-managers

Really bad developer experience if you're not using one trust.

**Additional context**
osano.com

**Comment by bardisg** [comment]
Hello @ecasilla ,

Thank you for your contribution! 

We do aim to support more consent managemnt platforms in the near future and @arnab-p will get back to you with more details.

**Comment by arnab-p** [comment]
@ecasilla,

Nice to meet you. I'm the Product Manager of the SDKs. I'd like to talk with you about the next steps here. Would you mind blocking a time [here](https://calendly.com/arnab-rudderstack/connect) at your convenience? 

Cheers!
Arnab
