### ISSUE TITLE
How we can set the destination would be the API or Kakfa ?

### ISSUE THREAD

**Issue by prk2331** [rudderlabs/rudder-sdk-js#943]
Hi team ,
    Can you please guide me, how can  I test to test this into my local.
    and where Can I configure the destination in the code to API or Kafka topic.
    I'm making a college project where I have a basic android app and I want this library to capture real time events to ingest the data in to my DB real time.

Thanks

**Comment by pallabmaiti** [comment]
Hey @prk2331 please use our [Slack](https://resources.rudderstack.com/join-rudderstack-slack) for any kind of help or support.
